#!/bin/bash -e

XTRACE="-x"
shopt -u -o | grep xtrace > /dev/null && XTRACE="+x"

set +x

die()
{
  echo $1
  exit 1
}

for arg in "$@"; do
  case $arg in

    --mwp-zip=*)
      MWP_ZIP="${arg#*=}";
      shift;;

    --clean)
      clean="1"
      shift;;

  esac
done

set $XTRACE

if [ -n "$clean" ]; then

  ant clean

  cd libs
  rm -rf *
  cd ..

else

  # Prep this dir for building
  test -z "$MWP_ZIP" && die "Zip file needed: --mwp-zip=blah.zip"

  unzip $MWP_ZIP
  test -d include && rm -rf include

fi

