#!/bin/bash -e

# WORKSPACE is the name of the dir on Jenkins
test -n "$WORKSPACE" || export WORKSPACE="$(pwd)/.."
test -n "$BUILD_NUMBER" || export BUILD_NUMBER="1"
test -n "$USER"         || export USER="none"

for arg in "$@"; do
  case $arg in

    --skip-tests)   SKIP_TESTS="1";     shift;;

  esac
done

echo "Workspace dir: $WORKSPACE"
echo "Build Number: $BUILD_NUMBER"


OUTPUT_DIR="$WORKSPACE/client/deliveries/ios/cpl"
rm -rf ${OUTPUT_DIR}
mkdir -p ${OUTPUT_DIR}
echo "Output Dir: $OUTPUT_DIR"

if [ -z "$SKIP_TESTS" ]; then
  xcodebuild -project ${WORKSPACE}/client/src/ios/HPControlledPrint/HPControlledPrint.xcodeproj -scheme HPControlledPrint ARCHS="i386 x86_64" VALID_ARCHS="i386 x86_64 armv7 arm64" -configuration Release ONLY_ACTIVE_ARCH=NO CONFIGURATION_BUILD_DIR="${OUTPUT_DIR}/simulator" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build test
else
  xcodebuild -project ${WORKSPACE}/client/src/ios/HPControlledPrint/HPControlledPrint.xcodeproj -scheme HPControlledPrint ARCHS="i386 x86_64" VALID_ARCHS="i386 x86_64 armv7 arm64" -configuration Release ONLY_ACTIVE_ARCH=NO CONFIGURATION_BUILD_DIR="${OUTPUT_DIR}/simulator" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build
fi

xcodebuild -project ${WORKSPACE}/client/src/ios/HPControlledPrint/HPControlledPrint.xcodeproj -scheme HPControlledPrint -sdk iphoneos8.4 ARCHS="armv7 arm64" VALID_ARCHS="i386 x86_64 armv7 arm64" -configuration Release ONLY_ACTIVE_ARCH=NO CONFIGURATION_BUILD_DIR="${OUTPUT_DIR}/device" clean build || \
  xcodebuild -project ${WORKSPACE}/client/src/ios/HPControlledPrint/HPControlledPrint.xcodeproj -scheme HPControlledPrint ARCHS="armv7 arm64" VALID_ARCHS="i386 x86_64 armv7 arm64" -configuration Release ONLY_ACTIVE_ARCH=NO CONFIGURATION_BUILD_DIR="${OUTPUT_DIR}/device" clean build

cp -R ${OUTPUT_DIR}/device/ ${OUTPUT_DIR}/release
cd $OUTPUT_DIR
lipo $OUTPUT_DIR/simulator/HPControlledPrint.framework/HPControlledPrint $OUTPUT_DIR/device/HPControlledPrint.framework/HPControlledPrint -create -output $OUTPUT_DIR/release/HPControlledPrint.framework/HPControlledPrint

cd $OUTPUT_DIR/release
zip --recurse-paths HPControlledPrint.framework_0.40_$BUILD_NUMBER.zip HPControlledPrint.framework
