#!/bin/bash -e

test -n "$JENKINS_HOME" && set -x

XTRACE="-x"
shopt -u -o | grep xtrace > /dev/null && XTRACE="+x"

set +x          # Stop logging while we are parsing the options

for arg in "$@"; do
  case $arg in

    --release-only)
      RELEASE_ONLY="1"
      shift;;

    --dev)
      DEVELOPMENT="1"
      shift;;

    --install)
      install="1"
      shift;;

  esac
done

test -n "$JENKINS_HOME" && RELEASE_ONLY="1"

set $XTRACE     # Restart logging

START_DIR=$(pwd)

if [ -z "$DEVELOPMENT" ]; then

  # clean the jni/NDK stuff
  cd src/java && ndk-build clean && ant clean
  cd $START_DIR

  # Then build the release version
  $(dirname $0)/build-android-release

  # On the build server, just do the release build
  if [ -z "$RELEASE_ONLY" ]; then
    # clean the jni/NDK stuff
    cd src/java && ndk-build clean && ant clean
    cd $START_DIR

    # Then build the debug version
    $(dirname $0)/build-android-debug
  fi

else

  $(dirname $0)/build-android-debug --dev
fi

