#!/usr/bin/env bash

kill_dir()
{
  if [ -d "$1" ]; then rm -rf $1; fi
}

test -n "$WORKSPACE" || export WORKSPACE="$(pwd)/.."

kill_dir ${WORKSPACE}/client/cmake-build/ios_simulator
kill_dir ${WORKSPACE}/client/cmake-build/ios_simulator64
kill_dir ${WORKSPACE}/client/cmake-build/ios_device
kill_dir ${WORKSPACE}/client/deliveries/ios

