#!/bin/bash -e

test -n "$JENKINS_HOME" && set -x

XTRACE="-x"
shopt -u -o | grep xtrace > /dev/null && XTRACE="+x"

die()
{
  echo "$*"
  exit 1
}

DEBUG_RELEASE=debug
#PLATFORM=
#OS=

for arg in "$@"; do
  case $arg in

    --type=*)
      DEBUG_RELEASE="${arg#*=}";
      shift;;

    --platform=*)
      PLATFORM="${arg#*=}";
      shift;;

    --os=*)
      OS="${arg#*=}";
      shift;;

    --build-tool=*)
      BUILD_TOOL="${arg#*=}";
      shift;;
  esac
done

# -------------------------------------------------------------
# ---------- Make sure we have the proper parameters ----------
test -n "$DEBUG_RELEASE" || die "must specify --type=debug or --type=release"
test -n "$OS"            || die "must specify --os=xyz    (ios, android)"
test -n "$PLATFORM"      || die "must specify --platform=xyz    (simulator, device)"
test -n "$BUILD_TOOL"    || die "must specify --build-tool=xyz     (xcode, android-ndk)"

set $XTRACE     # Restart logging

# WORKSPACE is the name of the dir on Jenkins
test -n "$WORKSPACE" || export WORKSPACE="$(pwd)/.."
test -n "$BUILD_NUMBER" || export BUILD_NUMBER="1"
test -n "$USER"         || export USER="none"

echo "Workspace dir: $WORKSPACE"
echo "Packaging $DEBUG_RELEASE $PLATFORM $OS $BUILD_TOOL"




# -------------------------------------------------------------
# ---------- Package it up ----------

# Zip up the libs
cd ${WORKSPACE}/client/deliveries/${OS}/${PLATFORM}/${DEBUG_RELEASE}
zip --recurse-paths mwp_sap_cpl-${OS}-${PLATFORM}-${DEBUG_RELEASE}_1.1-${BUILD_NUMBER}.zip libs

# Zip up the headers
cd ${WORKSPACE}/client/deliveries
zip --recurse-paths ${WORKSPACE}/client/deliveries/${OS}/${PLATFORM}/${DEBUG_RELEASE}/mwp_sap_cpl-${OS}-${PLATFORM}-${DEBUG_RELEASE}_1.1-${BUILD_NUMBER}.zip include

# Put the zip file into the base delivery dir
cd ${WORKSPACE}/client/deliveries/${OS}
mv ${PLATFORM}/${DEBUG_RELEASE}/mwp_sap_cpl-${OS}-${PLATFORM}-${DEBUG_RELEASE}_1.1-${BUILD_NUMBER}.zip ./

cp mwp_sap_cpl-${OS}-${PLATFORM}-${DEBUG_RELEASE}_1.1-${BUILD_NUMBER}.zip mwp_sap_cpl-${OS}-${PLATFORM}-${DEBUG_RELEASE}_1.1-latest.zip

#rm    ${PLATFORM}/${DEBUG_RELEASE}/libs/*
#rmdir ${PLATFORM}/${DEBUG_RELEASE}/libs
#rmdir ${PLATFORM}/${DEBUG_RELEASE}
#rmdir ${PLATFORM}

